--
-- Table structure for table `leaderboard`
--

CREATE TABLE `leaderboard` (
  `user` varchar(50) NOT NULL,
  `Structured Programming Language` int(11) NOT NULL DEFAULT 0,
  `Structured Programming Language Total` int(11) NOT NULL DEFAULT 0,
  `Discrete Math` int(11) NOT NULL DEFAULT 0,
  `Discrete Math Total` int(11) NOT NULL DEFAULT 0,
  `Data Structures` int(11) NOT NULL DEFAULT 0,
  `Data Structures Total` int(11) NOT NULL DEFAULT 0,
  `Algorithm Design & Analysis` int(11) NOT NULL DEFAULT 0,
  `Algorithm Design & Analysis Total` int(11) NOT NULL DEFAULT 0,
  `Object Oriented Programming` int(11) NOT NULL DEFAULT 0,
  `Object Oriented Programming Total` int(11) NOT NULL DEFAULT 0,
  `Numerical Analysis` int(11) NOT NULL DEFAULT 0,
  `Numerical Analysis Total` int(11) NOT NULL DEFAULT 0,
  `Theory of Computation` int(11) NOT NULL DEFAULT 0,
  `Theory of Computation Total` int(11) NOT NULL DEFAULT 0,
  `Ethics & Cyber Law` int(11) NOT NULL DEFAULT 0,
  `Ethics & Cyber Law Total` int(11) NOT NULL DEFAULT 0,
  `Digital Signal Processing` int(11) NOT NULL DEFAULT 0,
  `Digital Signal Processing Total` int(11) NOT NULL DEFAULT 0,
  `Database System` int(11) NOT NULL DEFAULT 0,
  `Database System Total` int(11) NOT NULL DEFAULT 0,
  `Operating System` int(11) NOT NULL DEFAULT 0,
  `Operating System Total` int(11) NOT NULL DEFAULT 0,
  `Computer Networking` int(11) NOT NULL DEFAULT 0,
  `Computer Networking Total` int(11) NOT NULL DEFAULT 0,
  `Computer Graphics` int(11) NOT NULL DEFAULT 0,
  `Computer Graphics Total` int(11) NOT NULL DEFAULT 0,
  `Computer Architecture` int(11) NOT NULL DEFAULT 0,
  `Computer Architecture Total` int(11) NOT NULL DEFAULT 0,
  `Artificial Intelligence` int(11) NOT NULL DEFAULT 0,
  `Artificial Intelligence Total` int(11) NOT NULL DEFAULT 0,
  `Machine Learning` int(11) NOT NULL DEFAULT 0,
  `Machine Learning Total` int(11) NOT NULL DEFAULT 0,
  `Others` int(11) NOT NULL DEFAULT 0,
  `Others Total` int(11) NOT NULL DEFAULT 0,
  `any` int(11) NOT NULL DEFAULT 0,
  `any Total` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
